name: Build App
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      working-directory: solution
      run: nuget restore AA2PersonalityDisorder.sln

    - name: Build solution
      working-directory: solution
      run: msbuild AA2PersonalityDisorder.sln /p:Configuration=Release /m

    - name: Upload Release build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: AA2PersonalityDisorder-Release
        path: |
          solution/**/bin/Release/**
